### ISSUE TITLE
N3ds ver 10.7.0.32U Smash ver 1.0.4 - Smashhax not working

### ISSUE THREAD

**Issue by ghost** [yellows8/3ds_smashbroshax#17] opened 2016-03-27 19:30 UTC
I had it working a long while ago on v 1.1.2, but I can't ever get it to work on 1.0.4. I deleted the new update data, and when I boot it tries to force me to update. I can play the game without save data and it creates extra data. At this point everything is ready and when I go into group, the game crashes or just doesn't do anything. I have two SD cards and on my second one (32gb Samsung) the game crashes. When I go back in it has an error and resets the data. On the first one (4gb Toshiba that came with the 3DS) it doesn't do anything. I even tried resetting the Toshiba and it doesn't work. Nervous to reset the Samsung because I have game save data. Please help me, thank you.

**Comment by Guriam** [comment] 2016-03-27 23:59
Having the same problem here. I'm on 1.0.4, everything on linux is right. the game crashes but doesn't go to homebrew.
Using physical copy of the game.
Did everything from zero about a dozen times, same results.
 Thanks in advance

**Comment by miguelgfreitas** [comment] 2016-04-22 12:34
The same is happening to me. I'm trying to run this on 10.7 FW with a 1.1.0 cartridge and although everything seems to be working fine, the moment the ds catches the packet, the game just crashes without launching the homebrew.

**Comment by griryu** [comment] 2016-04-22 15:08
Exact same issue for me on the 1.1.0 EU version of the game. It just crashes and takes me back to home menu afterwards. Really hope this is just an issue with my wireless as i don't have any access to run OOTHax.

**Comment by Flagers** [comment] 2016-05-10 02:54
This may be a duplicate of another issue ticket

**Comment by yellows8** [comment] 2016-05-27 16:00
#13

**Closed as completed by yellows8** 2016-05-27 16:00 UTC

**Comment by goldroger45** [comment] 2016-10-31 23:49
I'm having the same issue and I don't seem to find the solution online. N3ds ver 10.7.0.32U Smash ver 1.0.4 with ubuntu mate 15.04. 
I'm able to send packets but when I click on groups I keep getting this error "An error has occurred, forcing the software to close. The system will now restart. (unsaved data may be lost.)" 
The 3ds ask to update the game every time that I open it. I'm stuck, I have seem a video suggesting to use another pcap file if I have the USA version 1.0.4 but they don't mention which one. I also have the starter kit, the payload. Any suggestions? Thank you
